[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'vim-denops/denops-helloworld.vim'

[[plugins]]
repo = 'Shougo/ddu.vim'
hook_add = '''
nnoremap <silent> <Leader><Leader>n :<C-u>call ddu#start({}) <CR>
autocmd FileType ddu-filer call s:ddu_my_settings()
function! s:ddu_my_settings() abort
  nnoremap <buffer><silent> <CR>
        \ <Cmd>call ddu#ui#filer#do_action('itemAction')<CR>
  nnoremap <buffer><silent> <Space>
        \ <Cmd>call ddu#ui#filer#do_action('toggleSelectItem')<CR>
  nnoremap <buffer> o
        \ <Cmd>call ddu#ui#filer#do_action('expandItem',
        \ {'mode': 'toggle'})<CR>
  nnoremap <buffer><silent> q
        \ <Cmd>call ddu#ui#filer#do_action('quit')<CR>
endfunction

call ddu#custom#patch_global({
    \   'ui': 'filer',
    \   'uiParams': {'filer': {'split': 'floating'}},
    \   'sources': [{'name': 'file', 'params': {}}],
    \   'sourceOptions': {
    \     '_': {
    \       'columns': ['filename'],
    \     },
    \   },
    \   'kindOptions': {
    \     'file': {
    \       'defaultAction': 'open',
    \     },
    \   }
    \ })
'''

[[plugins]]
repo = 'Shougo/ddu-ui-filer'


[[plugins]]
repo = 'Shougo/ddu-source-file'

[[plugins]]
repo = 'Shougo/ddu-kind-file'

[[plugins]]
repo = 'Shougo/ddu-column-filename'


[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
		let g:lightline = {
				\ 'colorscheme': 'molokai',
				\ 'component': {
				\   'lineinfo': ' %3l:%-2v',
				\ },
				\ 'component_function': {
				\   'readonly': 'LightlineReadonly',
				\   'fugitive': 'LightlineFugitive'
				\ },
				\ 'separator': { 'left': '', 'right': '' },
				\ 'subseparator': { 'left': '', 'right': '' }
				\ }
		function! LightlineReadonly()
				return &readonly ? '' : ''
		endfunction
		function! LightlineFugitive()
				if exists('*fugitive#head')
						let branch = fugitive#head()
						return branch !=# '' ? ''.branch : ''
				endif
				return ''
		endfunction
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
		let g:quickrun_config = {}
		let g:quickrun_config.markdown = {
				\ 'type': 'markdown/pandoc',
				\ 'cmdopt': '-s',
				\ 'outputter': 'browser'
				\ }
'''


[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
let g:EasyMotion_do_mapping = 0 

" Jump to anywhere you want with minimal keystrokes, with just one key binding.
" `s{char}{label}`
nmap <Leader><Leader> [easymotion-kidou]
nmap [easymotion-kidou]g <Plug>(easymotion-overwin-f)
" or
" `s{char}{char}{label}`

" Turn on case-insensitive feature
let g:EasyMotion_smartcase = 1

" JK motions: Line motions
map [easymotion-kidou]j <Plug>(easymotion-j)
map [easymotion-kidou]k <Plug>(easymotion-k)
'''
